### ISSUE TITLE
Autoload in Chrome image jump on drag

### ISSUE THREAD

**Issue by Stef0803** [mpetroff/pannellum#876] opened 2020-06-03 10:06 UTC
Hello,

When i use autoload in Chrome and first time drag on image it jumps to fullscreen without the posibility to go back.
This problem doesn't arise in other browsers

How can i solve this? 
For a customer, we temporarily disabled autoload because then the problem will not arise.

_Testcase: https://www.goesenroos.nl/case/pannellum/pannellum.html
Button 360 opens modalbox in Chrome if you want to drag the photo it jumps to fullscreen._

_Browser versions:
Google Chrome, Version 83.0.4103.61 (Official Build) (64-bit)
Firefox, Version 77.0 (64-bit)
Microsoft Edge_

**Comment by mpetroff** [comment] 2020-06-03 14:44
This is an issue with your page, not Pannellum. As you have Pannellum in an `<iframe>`, it can't possibly be the cause of your issue.

This isn't a general web design support forum, so I'm closing this issue for being out of scope. Even though I didn't need to, I took a brief look at your page. Your issue seems to be related to your `.modal-360 iframe {height: 100% !important;}` CSS rule. This is poorly written CSS, so I'm not surprised it's causing issues; `!important` should only by used to override external CSS, not other rules in your own CSS. If you set the `<iframe>` height to `100%` instead of `100% !important`, it doesn't display the issue.

**Closed by mpetroff** 2020-06-03 14:44 UTC

**Comment by Stef0803** [comment] 2020-06-03 18:56
Oh no how stupid of me.
Thanks for investigating anyway.

Sorry for wasting your time and looking at my mess.
