### ISSUE TITLE
Req: Stereo Effect

### ISSUE THREAD

**Issue by dmzone** [mpetroff/pannellum#335] opened 2017-01-30 10:44 UTC
Is there a way to switch to Cardboard mode with StereoEffect.js?

**Comment by mpetroff** [comment] 2017-02-05 22:59
As far as I can tell, the "StereoEffect.js" you're referring to is part of three.js; as Pannellum doesn't use three.js, it's not applicable.

Support for Google Cardboard is a duplicate of #82.

**Closed by mpetroff** 2017-02-05 22:59 UTC
