### ISSUE TITLE
Fullscreen not available in iOS

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#467] opened 2017-08-30 17:55 UTC
Apparently the fullscreen button is missing in iOS (e.g. Safari). 
The motion sensor button is shown, but it is probably not related to fullscreen mode.

**Comment by mpetroff** [comment] 2017-08-30 18:23
Duplicate of #313, #309 and #66. iOS doesn't support the full screen API: http://caniuse.com/#feat=fullscreen

**Closed by mpetroff** 2017-08-30 18:23 UTC
