### ISSUE TITLE
Ipad Pannellum viewing skewed

### ISSUE THREAD

**Issue by gbarmus** [mpetroff/pannellum#77] opened 2015-06-03 14:58 UTC
First of all, I'm not a techhead by any stretch but I absolutely love Pannellum. I'm done with using flash and this is perfect. So I've been working with a few spheres on my website... turning into tours and having fun. I grabbed my ipad to view the images and they seem to be loading fine but rendering them skewed. At first I thot it was just my own panos and started looking into resolution and size limitations as well as resizing issues etc but then i came upon this thread (https://github.com/mpetroff/pannellum/issues/25). On that thread, the example has a pano here: http://www.vraccess.co.uk/?p=29 which works perfectly on computer but on ipad the image has grainy lines - the same that's happening with my spheres. So I decided to take a screenshot (http://pianopricepoint.com/pannellum-ipad-screen.png). As mentioned, everything seems to be loading properly, it's just that the view is skewed and the image has only a narrow rotation of what appear to be the top of the image. Any thoughts around this? Cheers

**Comment by mpetroff** [comment] 2015-06-04 03:04
As far as I can tell, it's a bug in Apple's WebGL implementation for iOS. It seems to have a tendency of silently failing and giving weird results instead of throwing an error. Since the last release, I've added checks that catch some of these errors. I'll try this image with the development version once I have access to an iOS device again (in about two weeks).

**Comment by gbarmus** [comment] 2015-06-04 04:54
Thank you so much for looking into this. Oddly enough, the image on the pannellum.org page works fine on ipad.

**Comment by mpetroff** [comment] 2015-06-05 02:29
The panorama on pannellum.org is a multires panorama that uses small tiles, so no devices have texture size issues (which I suspect might be why the other panorama doesn't display properly).

For your other question, #12 added support for this, but I don't have any examples (and it might be broken as I've never tested it). Adding either an `image` or a `video` parameter with the image/video's URL to the hotspot's configuration should provide the desired functionality.

**Comment by gbarmus** [comment] 2015-06-05 16:31
I'll do some testing on this. Would this code already be implemented into the latest version or would I need to download something newer than 2.1.1? Cheers

**Comment by mpetroff** [comment] 2015-06-07 01:45
It's in 2.1.1.

**Comment by mpetroff** [comment] 2015-07-06 00:58
After doing some testing, it seems to be due to a bug in Apple's WebGL implementation. Only progressive JPEGs seem to work, with standard JPEGs producing the pattern described in this bug report. I only tried a couple images, so I'm not positive this is the cause, but if it is, there's nothing I can do about it.

**Comment by mpetroff** [comment] 2015-12-23 19:16
This seems to have been fixed in iOS 9. I added in a check to display an error message in iOS 8, though.

**Closed by mpetroff** 2015-12-23 19:16 UTC
Labels: bug
