### ISSUE TITLE
Overlay effects, layer two images together

### ISSUE THREAD

**Issue by L00ncan** [mpetroff/pannellum#1092] opened 2022-04-15 16:51 UTC
This is not the same question asked by [/mpetroff/pannellum/issues/1051](https://github.com/mpetroff/pannellum/issues/1051) - titled (Multiple image selection overlay support)   - i'm looking for something alot different like layer options for photographers, i'm interested for my photography interest in Astronomy, just so we're clear :)

Very impressed with your Panorama Player but it would be awesome if we could get options to overlay effects such as custom made special effects over images, a simple transparent image (.png or animated .gif) of equal dimensions overlayed example over my collections of Saturns moons images would be awesome, i could change the orbits overlay on the fly, i want to start collecting astronomy 3d pictures and options to overlay glares, debris etc;- animated gif 3d dust would be epic, sadly it seems the only way to currently do it is have custom individual webcoded pages for each individual image which dealing with hundreds of thousands of nasa pics would be a headache. Simple overlays dimensionally matched changed by url code would be uniquely fun.  I love your Panorama player i truly do, but a simpler way to overlay an image. Whomever cracks this novel layer approach leaves the realm of simple Panorama players to custom Panorama 3d special effect enchanter. Photoshop 3.0 1994 only evolved & hit the charts when it introduced layers afterall. Photoshop 3.0 still is the current pinnacle thresshold of ideas from them, they haven't really improved since 1994 3.0 when you breakdown what photoshop is. Photoshop 3.0 was when they introduced layers. 

See yourself https://www.youtube.com/watch?v=4dp8tdt2hPM  _<-youtube video of photoshop evolving throughout the years_

the most i can add to my url is this // hfov=120&autoRotate=-13&autoLoad=true

If i could add an external overlay by using the url code instead of hardcoding pages, html, php, scripts and styles i was able to just overlay another image (two images) using plain url bar within the url bar would really make software consumers really take notice just like Photoshop 3.0 did.

Url options to overlay an equal sized image would be epic

**Comment by mpetroff** [comment] 2022-04-24 01:09
If you draw equirectangular images to a `<canvas>` and provide the `<canvas>` to Pannellum, you can draw whatever you want. This is a duplicate of #743.

As for URL parameters, you'd have to use Pannellum's API and do your own parameter handling.

**Closed** 2024-10-05 15:41 UTC
Labels: question
