### ISSUE TITLE
Play sound on mousedown and change file with scene change?

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#966] opened 2021-03-13 15:05 UTC
Hi. Is there someway to utilize the mousedown event in order to change the source of an audio tag when the scene changes? 

I’ve got about 25 scenes, and for each scene I want a different looping sound to play on mousedown. Is there someway to say “during this scene play this file on mousedown, then during this other scene play this other file on mousedown…etc.…“?

**Comment by strarsis** [comment] 2021-03-13 15:31
@epignosis567: Well, as I posted in the other issue, you could add a custom field to the scenes of your tour JSONk, e.g. `playSound` with an URL to each sound file. Then a single JavaScript handler can use that field and play back the sound, if one is set for that scene.

**Comment by mpetroff** [comment] 2021-03-13 17:06
This question is effectively a duplicate of #964. I'm closing this issue as I'd prefer to keep the discussion in one place.

**Closed by mpetroff** 2021-03-13 17:06 UTC

**Comment by epignosis567** [comment] 2021-03-13 17:12
Sorry, I did search the issues first! I have no idea how I missed that.
