### ISSUE TITLE
The clickHandlerFunc event does not take effect on the mobile terminal

### ISSUE THREAD

**Issue by SleepyShark709** [mpetroff/pannellum#926] opened 2020-10-16 10:02 UTC
Hi Matthew

Hope all is well. 

I have a question, on mobile terminal, the clickHandlerFunc not work

my code is: 
`"clickHandlerFunc": this.HotSpotClickHandler

   HotSpotClickHandler (){
                setTimeout(() => {
                    this.Pannellum.setHfov(90, 1500)
                }, 1)
   }
`

I use Vue framework, which can work normally in the web environment of PC, but it doesn't work on mobile terminal

**Comment by mpetroff** [comment] 2020-10-16 14:12
This is a duplicate of the bug reported in #861. It was fixed in 6075769935a27e61c9e1f0f656f8cef532abaa77, but the fix has not yet made it into a release.

**Closed by mpetroff** 2020-10-16 14:12 UTC

**Comment by SleepyShark709** [comment] 2020-10-19 03:56
Matthew, thank you for your reply

I imported the local JS file according to your reply, but the function still can't be executed.

The touchend event of the source code can be executed, but the hs.clickHandlerFunc (e,  hs.clickHandlerArgs ）; it doesn't seem to be implemented.

Because on the mobile terminal, I want to setHfov, but it still has no effect

**Comment by SleepyShark709** [comment] 2020-10-19 06:22
I solved this problem,
Add a setTimeout timer to the touchend event in the source code
