### ISSUE TITLE
Fisheye

### ISSUE THREAD

**Issue by peterpan666** [mpetroff/pannellum#265] opened 2016-10-06 11:16 UTC
Hi and thanks for this awesome library!

I think I don't get all of this but it seems that it's not possible to have a fish eye effect with your library am I right?

Here is two pictures, the first one is from Theta website ([original link](https://theta360.com/spheres/samples/2bccbf6a-89ee-11e6-bbb7-064087ff3472-1))

![Theta](https://cloud.githubusercontent.com/assets/4153168/19150376/ced36810-8bc6-11e6-8b9f-03da23314ee8.png)

And here is the one I got with pannellum

![Pannellum](https://cloud.githubusercontent.com/assets/4153168/19150402/ed1f05b8-8bc6-11e6-8d07-4ee9989f2199.png)

The two have the same zoom level but the effect is very different.. Is it possible to this with pannellum? Did I miss something?

**Comment by mpetroff** [comment] 2016-10-06 14:19
This is a duplicate of #52. The Ricoh viewer transitions from rectilinear projection to stereographic projection when zoomed out enough. It's something I hope to get to eventually.

**Closed by mpetroff** 2016-10-06 14:19 UTC

**Comment by peterpan666** [comment] 2016-10-06 15:31
Yep thanks to point it out! Thanks for your answer and keep on the good work ;)
