### ISSUE TITLE
autoRotate speed varies from device to device

### ISSUE THREAD

**Issue by victorclaessen** [mpetroff/pannellum#146] opened 2016-05-02 10:17 UTC
Hi,

The autoRotate speed seems to vary between devices. On my desktop browser (Chrome), the autoRotation is  faster (by about a factor of 2) than on my (fairly modern and fast) android device (also Chrome). Do you know what might be causing that?

Best regards,

Victor

**Comment by mpetroff** [comment] 2016-05-02 12:29
I don't know why this would happen. The amount to rotate for each new frame is calculated using the time difference from the previous frame, not a fixed amount, so the speed should be independent of frame rate or device used.

**Comment by strarsis** [comment] 2016-05-02 14:43
I have the same issue - except that it also occurs on some higher end PCs (Chrome + Firefox), 
rotating with different speed on different systems.
It seems to be caused by different CPU/GPU load - maybe requestAnimationFrame could help with this?

**Comment by mpetroff** [comment] 2016-05-02 16:22
`requestAnimationFrame` is already being used to determine when to draw a new frame. To determine the amount to rotate for each new frame, the time between frames is needed, which is calculated using timestamps from `performance.now()` (or `Date.now()` if `performance.now()` isn't available).

**Comment by jannecederberg** [comment] 2016-06-15 06:26
Could the initial question possibly have been addressed by #163 ? Could you @victorclaessen pull changes from master and see if you still see the same difference in autoRotate speed between desktop and mobile?

**Comment by victorclaessen** [comment] 2016-07-04 13:39
I can confirm that the autoRotate speed is now the same on both devices.

**Comment by jannecederberg** [comment] 2016-07-04 14:54
Ok, cool

**Closed** 2019-07-13 22:55 UTC
Labels: question
