### ISSUE TITLE
Tour scene image is broken when switching browser tab - macOS Mojave

### ISSUE THREAD

**Issue by reviewingcode** [mpetroff/pannellum#837] opened 2020-02-26 15:58 UTC
I'm not sure if this is a bug with pannellum or some other issue with OS, GPU etc.
Please take a look at the attached [Screen Recording.zip](https://github.com/mpetroff/pannellum/files/4256361/Screen.Recording.zip).

**Any idea what might have caused this?**

App is basically a pannellum tour (`type: 'equirectangular'`) with some custom elements placed on top of the scene image with CSS position.

Relevant config:
```
 capturedKeyNumbers: [17, 27, 37, 39, 61, 65, 68, 83, 87, 107, 109, 173, 187, 189],
 friction: 1,
 ignoreGPanoXMP: true,
 default: {
   firstScene: '2',
   autoLoad: true
 }
```

The problem appeared on a system running `macOS Mojave`, with chrome `Version 79.0.3945.130 (Official Build) (64-bit)`. It has since gone away after an OS upgrade to `macOS Catalina`.

System details:
![system](https://user-images.githubusercontent.com/36093197/75361492-2fb8a900-58d9-11ea-9522-c66ff4aedfb7.jpg)

**Comment by mpetroff** [comment] 2020-02-29 00:56
Are there any errors or warnings printed to the browser's developer console? This looks like a browser bug to me.

**Comment by reviewingcode** [comment] 2020-02-29 12:43
No errors or warnings. Nothing printed to the browser's developer console.

**Comment by mpetroff** [comment] 2020-02-29 20:25
I am unable to reproduce this using Sauce Labs. As there are no messages, there's not much I can do if I can't reproduce the issue.

As this appears to be a bug specific to a particular browser / OS combination that is now outdated, I'm going to close this issue. It can be reopened if new information comes to light, or if other people are able to reproduce the issue.

**Closed by mpetroff** 2020-02-29 20:25 UTC
