### ISSUE TITLE
setYaw function

### ISSUE THREAD

**Issue by choiyoonho2** [mpetroff/pannellum#473] opened 2017-09-13 04:07 UTC
I'm implementing a function that when I click the screen with the mouse, to set the yaw value to the clicked position. I used setYaw function and the function worked well when both value (config.yaw , clicked yaw position) are positive number or negative number. However, when either is positive or negative, the camera rotates to the opposite side and the yaw is set.
![image](https://user-images.githubusercontent.com/12508396/30359223-2bf2fd6a-9884-11e7-80e0-f78225895440.JPG)
What parts should be fixed?

**Comment by mpetroff** [comment] 2017-09-13 23:54
Duplicate of #315. This has already been fixed in the development version.

**Closed by mpetroff** 2017-09-13 23:54 UTC
