### ISSUE TITLE
(safari/iOS)If picture size is more than 5800 px wide, it's not working.

### ISSUE THREAD

**Issue by ishikawamb** [mpetroff/pannellum#795] opened 2019-09-23 09:03 UTC
Please look at attachment file.
If the picture size is more than 5800px wide, it's not working on safari.

Would you ket me know what is the reason for this bug?
Is there a method to use this library on safari with more than 5800 px wide?
![pannellum_error](https://user-images.githubusercontent.com/52645802/65412912-66663100-de1a-11e9-937d-6fab09133cf7.jpg)

**Comment by mpetroff** [comment] 2019-09-24 16:27
What version of Pannellum are you using?

**Comment by ishikawamb** [comment] 2019-09-25 05:42
@mpetroff 
I'm using Pannellum 2.5.3.

**Comment by mpetroff** [comment] 2019-09-25 13:09
Okay. This is then a duplicate of #785, which was fixed in 2.5.4. Please update to the latest version.

**Comment by ishikawamb** [comment] 2019-10-01 08:34
It's solved.
Thank you so much!!!

**Closed** 2019-10-02 01:39 UTC
