### ISSUE TITLE
Low frame rate when autorotate in multi resolution?

### ISSUE THREAD

**Issue by 5h177y** [mpetroff/pannellum#930] opened 2020-10-22 10:12 UTC
Hi Matthew, thanks for all the great work, been very satisfied with Pannellum's perfomance and functionality
Recently I'm facing this issue which is the auto rotate in multi resolution is not quite smooth on pc (mobile works fine), have to force chrome to use my nvidia GPU then the result is great
Compared to other framework which is using three.js (same image), with Intel only still work much smoother than Pannellum
Anyway to improve besides lowering down the speed?
An example link:
https://cdn.pannellum.org/2.5/pannellum.htm#config=https://pannellum.org/configs/multiresolution.json&autoRotate=-10

**Comment by mpetroff** [comment] 2020-10-23 22:32
Comparing the performance of Pannellum's multiresolution mode with a non-multiresolution three.js viewer is not a fair comparison, since displaying a multiresolution image requires a significantly greater number of textures and draw calls (the apples-to-apples comparison would be Pannellum's equirectangular mode).

I'm going to categorize this as a duplicate of #911, since jank with auto-rotate is a specific case of multiresolution performance issues. In regard to #911, I made some significant performance improvements for multiresolution panoramas last month, which should hopefully resolve the issues you're seeing. The improvements will be included in the next release, v2.6.

**Closed by mpetroff** 2020-10-23 22:32 UTC
