### ISSUE TITLE
lookAt for hotspot near "edge" of wrapped panorama will travel all the way around to center on it, rather than take shortest distance

### ISSUE THREAD

**Issue by rpcarson** [mpetroff/pannellum#507] opened 2017-11-20 19:57 UTC
If I have a hotspot near the "edge" of the panorama where it was wrapped together, and the center of the screen is on the other side of that edge, and I use lookAt with animation time to snap to the hotspot, the view will travel all the way around the panorama and snap to the hotspot from the opposite direction rather than travel the short distance which the user would expect it to travel.

**Comment by mpetroff** [comment] 2017-11-20 21:15
This is a duplicate of #315 (as #473 are #502). This has already been fixed in the development version.

**Closed by mpetroff** 2017-11-20 21:15 UTC
