### ISSUE TITLE
Multiclick on hotspot background 360 image not change

### ISSUE THREAD

**Issue by muhammadaamir** [mpetroff/pannellum#442] opened 2017-07-27 09:54 UTC
when i click multitimes on hotspot so back image wont change and it disable like drage wont work and hotspots is floating in air and it also happen with https://pannellum.org/ page panorama view

**Comment by mpetroff** [comment] 2017-08-02 00:33
This is a duplicate of #303, which has been fixed in the development version but is not yet in a release.

**Closed by mpetroff** 2017-08-02 00:33 UTC
