### ISSUE TITLE
Pannellum rotates 360 degrees to open the nearest clicked hotspot

### ISSUE THREAD

**Issue by Boochoo** [mpetroff/pannellum#502] opened 2017-11-07 08:05 UTC
Is there a way to make the library get to the nearest clicked hotspot rather than spinning a whole circle to open up the clicked hotspot ? This only happens if the clickable hotspots are near the end of the screen, where Yaw is either around 180 or -180; for example:- if Yaw is 175 or -175. I am just wondering if there's a better way that something like `  if (viewer.getYaw() < -170) {
    viewer.setYaw(-180);
  } else {
    viewer.setYaw(139);
  }` because if it rotates the other way around if it's less than -180.

**Comment by mpetroff** [comment] 2017-11-07 15:52
Duplicate of #315 and #473. This has already been fixed in the development version.

**Closed by mpetroff** 2017-11-07 15:52 UTC
