### ISSUE TITLE
minPitch / maxPitch incorrect constraints (defaults)

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#624] opened 2018-06-29 11:55 UTC
The `minPitch` and `maxPitch` options for constraining the viewer pitch, are 
added to configuration JSON file by pannellum generator script. 

The defaults are `"minPitch": -90` and `"maxPitch": 90`, 90 degrees should 
allow full freedom when pitching the view, but this is not the case. 
One cannot look completely down to nadir or up to zenith anymore. 

Instead, `minPitch` and `maxPitch` have to be removed to 
set them to `undefined` for full freedom when pitching.

**Comment by mpetroff** [comment] 2018-07-01 18:12
It should be fixed in 60c4d5d606774dbf2b67dbc5e3fbf6524b1a24f6.

**Closed** 2018-07-01 18:11 UTC
Labels: bug

**Comment by strarsis** [comment] 2018-07-04 14:48
@mpetroff: The fix prevents these min-/max-parameters being written to tour file, 
but shouldn't it also work without noticeable constraints with e,g, "minPitch": -90 and "maxPitch": 90 in viewer itself?

**Comment by mpetroff** [comment] 2018-07-04 17:49
The current behavior is the intended behavior, which agrees with the documentation of the min/max pitch parameters. Said parameters limit the edge of the view, not the center, so setting them at all prevents viewing the nadir / zenith.

**Comment by strarsis** [comment] 2018-07-04 18:12
@mpetroff: This makes sense. Just out of curiosity: What values could be used for unconstrained view? Or is only `null`/`undefined` allowing full view?

**Comment by mpetroff** [comment] 2018-07-06 14:53
The values need to be some sort of `NaN` for unconstrained view. Here's the relevant code: https://github.com/mpetroff/pannellum/blob/a99d4eaa1c935b5b34e8bb326bd8565efd3662b1/src/js/pannellum.js#L1448-L1463
