### ISSUE TITLE
Additional URL queries breaking the applet

### ISSUE THREAD

**Issue by mjhorvath** [mpetroff/pannellum#965] opened 2021-03-12 00:29 UTC
I tried linking to a Pannellum applet from Facebook.

Facebook automatically adds additional URL queries to the end of the URL and it is breaking Pannellum. Please fix!

For instance:

&fbclid=IwAR257h5OpNmxbKM_4yR9xM438K6Ks4rmbnHYqRegoNjjJQMvHoYQAFD7vbg

Result:

"An invalid configuration parameter was specified: fbclid"

**Comment by mpetroff** [comment] 2021-03-12 02:32
Duplicate of #939. It's the fault of Facebook's adware.

**Closed by mpetroff** 2021-03-12 02:32 UTC

**Comment by mpetroff** [comment] 2021-03-12 02:39
Is this a problem if you specify Pannellum's parameters as a location hash, i.e., use `#` instead of `?`? The standalone viewer will ignore `?` parameters if `#` is used. I block Facebook's adware, so I'm not about to test this.

**Comment by mjhorvath** [comment] 2021-03-13 06:57
Yes, using the hash sign worked. Thanks.

**Comment by mpetroff** [comment] 2021-03-13 12:40
Great. Using the location hash has been the preferred method since it was added in Pannellum 2.3, since it doesn't unnecessarily send the configuration parameters to the server. The examples on pannellum.org use `#`, but I never updated the examples included in this repository. I just did so now in 02424bdfa3f915c6eee4a2995d9fbd117e267732 and also added a note to the readme about the preferred method.
