### ISSUE TITLE
error on non-secure

### ISSUE THREAD

**Issue by gregmatys** [mpetroff/pannellum#941] opened 2020-12-16 10:20 UTC
When testing on non-secure website, getting `DeviceMotionEvent is not defined` error.

You should check if this event exists: ```typeof DeviceMotionEvent!=="undefined"``` before you check `DeviceMotionEvent.requestPermission`

**Comment by mpetroff** [comment] 2020-12-16 16:13
This was fixed months ago (9592d2ab7be749faf6f590b8c6034f42ccd3d0d9 / 1a390dfdb0028e38150b50661c816d02149f72ef) but has not yet made it into a release version. Duplicate of #846 and #872.

**Closed by mpetroff** 2020-12-16 16:13 UTC
