### ISSUE TITLE
Hotspots begin floating in tour. 

### ISSUE THREAD

**Issue by tobestar7** [mpetroff/pannellum#536] opened 2018-01-19 05:22 UTC
Hi mpetroff

I have been using Pannellum with great success; it is very cool. However I appear to have found a bug that I cannot solve. 

It even occurs in your [tour example](https://pannellum.org/documentation/examples/tour/). 

When you go full screen, and double click on the hotspot, the scene doesn't change and the hot spot (in my case several,) begin to float around the screen. 

Is this a Google bug? Or something that could have a work around?

Using Chrome Version 63.0.3239.132 

Many thanks. 

tobestar7

**Comment by tobestar7** [comment] 2018-01-19 05:24
Addnl:
This bug also affects delivery onto mobile phones

**Comment by mpetroff** [comment] 2018-01-19 23:41
Duplicate of #303, which has already been fixed (but the fix isn't in a release yet).

**Closed by mpetroff** 2018-01-19 23:41 UTC

**Comment by tobestar7** [comment] 2018-01-20 01:11
Thank you.
