### ISSUE TITLE
I want to capture the current screen.

### ISSUE THREAD

**Issue by choiyoonho2** [mpetroff/pannellum#491] opened 2017-10-13 07:21 UTC
Hello. I want to capture the current screen. However, the canvas of the pannellum is printed in black.
![test 1](https://user-images.githubusercontent.com/12508396/31534495-1a5da67a-b032-11e7-8e79-ca0337cb4a44.png)
Here is my code.
![default](https://user-images.githubusercontent.com/12508396/31534571-6fdbf584-b032-11e7-8106-d276ce6d84b1.JPG)
What is the problem?

**Comment by mpetroff** [comment] 2017-10-13 11:59
Duplicate of #448.

**Closed by mpetroff** 2017-10-13 11:59 UTC
