### ISSUE TITLE
Pano looks pixelated on iOS

### ISSUE THREAD

**Issue by alketii** [mpetroff/pannellum#484] opened 2017-09-22 14:23 UTC
Panos looks pixelated on iOS. Tried both Safari and Google Chrome. 
I don't know if its iOS issue or Panellum one.
Tested with iPhone 6+ and iPad (can't recall which version it was).

Images with iPhone 6+ and Samsung Note 5 side by side:
https://lut.im/gallery#orj2L7rxXr/azHSHyMgRoAojOsN.PNG,r82GpVfQsR/cVp3Nqbx8NTTk04U.png

**Comment by mpetroff** [comment] 2017-09-23 05:06
I can't reproduce this in Safari on an iPhone 5c running iOS 10.3.3.

Looking at the image, it appears that the device pixel ratio isn't being properly reported / recognized, so it isn't being treated as a retina display; however, without being able to reproduce the issue, this is just speculation.

**Comment by hamuslee** [comment] 2017-09-24 17:42
Hi, I have the same issue on my iPhone 7 Plus (iOS 10.3.3).
The screenshot is using a cubemap with dimension 2048 x 2048px for each of the image (total 6 images). The source images are very clear and in high-resolution. I tried to print out the window.devicePixelRatio and it returns 3 on my phone. 

What's missing to make Pannellum treat it as a retina display?

![68b6e89b-e74d-452a-b5c4-58a9f5128d31](https://user-images.githubusercontent.com/335008/30785050-bd81e4dc-a192-11e7-97fc-e702e9123d24.PNG)

**Comment by hamuslee** [comment] 2017-09-24 18:37
@alketii  I encountered the same issue and it is solved by using "multires" approach.
To use multires, you need generate.py to generate images in different zoom levels, I read this and it helped me a lot: https://github.com/mpetroff/pannellum/issues/391

**Comment by mpetroff** [comment] 2019-07-13 22:49
I believe this was fixed in 59893bc. See #725 (comment).

**Closed by mpetroff** 2019-07-13 22:49 UTC
Labels: bug
