### ISSUE TITLE
error in firefox 57(64bit) 

### ISSUE THREAD

**Issue by sunkainj** [mpetroff/pannellum#518] opened 2017-12-11 09:29 UTC
when I change scene Sometimes it happens

Error: WebGL warning: drawArrays: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive.

libpannellum.js: 570:13

// Draw using current buffer
gl.drawArrays(gl.TRIANGLES, 0, 6);

**Comment by mpetroff** [comment] 2017-12-11 16:20
Duplicate of #505.

**Closed by mpetroff** 2017-12-11 16:20 UTC
