### ISSUE TITLE
VR compatiblity 

### ISSUE THREAD

**Issue by s1mar** [mpetroff/pannellum#274] opened 2016-11-08 08:21 UTC
Hi, will there be a VR mode for this awesome library. I need to create a tour but in VR; if not, then does anyone know any alternatives!?

**Comment by mpetroff** [comment] 2016-11-08 19:19
"VR" is such a generic term that I don't really know what you're asking.

**Comment by s1mar** [comment] 2016-11-10 10:19
stereoscopic 3d view compatible with google cardboard

**Comment by mpetroff** [comment] 2016-11-10 15:16
In that case, this is a duplicate of #82. The answer is currently no.

**Closed by mpetroff** 2016-11-10 15:16 UTC
Labels: question
