### ISSUE TITLE
Auto-rotate stops rotation at yaw = (-)180

### ISSUE THREAD

**Issue by auriiolym** [mpetroff/pannellum#767] opened 2019-08-04 16:29 UTC
I've noticed the auto-rotation stops when the yaw is 180 or -180 degrees. It does seem to continue the yaw calculations when no rendering takes place (e.g. when I switch tabs). In that case, it continues the animation and again stops at yaw (-)180.

Setting the `maxYaw` value to something below 180 results in the proper reversal of the auto-rotation.

I'd think it would continue rotating. Either continue or reverse, but at least not just stop.

My most basic example while experiencing this is:
```
pannellum.viewer(element, {
    panorama: '<path to image>',
    autoRotate: -10,
})
```
I use the latest version.

Any suggestions? Am I missing something?

**Comment by mpetroff** [comment] 2019-08-04 17:29
Duplicate of #764.

**Closed by mpetroff** 2019-08-04 17:29 UTC
