### ISSUE TITLE
How to load images in the background

### ISSUE THREAD

**Issue by pratikbendale** [mpetroff/pannellum#829] opened 2020-02-10 13:29 UTC
Hi @mpetroff ,
I have an equirectangular viewer with dynamic images URL getting from API call, I want to preload images in the background one by one when the first image is getting displayed 
What I actually want
Is there a way to preLoad all the scenes when seeing one? For example, I enter the tour and while I'm seeing the first scene can the others be loaded in the background so when I change of scene it won't take as long as before?(Found this on one of the pannellum Issues)
How can I achieve this?

**Comment by mpetroff** [comment] 2020-02-11 23:12
This is essentially a duplicate of #739. Besides the suggestions in that issue, my only other suggestion is to use Pannellum's multiresolution format, since it was designed to reduce load times.

**Comment by pratikbendale** [comment] 2020-02-12 07:03
Thanks for the quick response.
I have dynamic images for the viewer I cannot directly use those images with Pannellum's multiresolution format. For that I have to convert equirectangular panorama image into Pannellum’s multiresolution format using the 'generate.py' But how can I do it inside an angular application 
Can you help me for this approach?

**Comment by mpetroff** [comment] 2020-02-13 23:11
If you can't use the multiresolution format, I'd handle the image loading yourself and pass them as `blob` URLs to Pannellum, as recommended in https://github.com/mpetroff/pannellum/issues/739#issuecomment-497766671.

**Comment by pratikbendale** [comment] 2020-02-26 07:31
Hi @mpetroff ,
I have done some R&D and manage to use dynamic images with multiresolution.
and now no need of image loading in the background.
Thanks for the support.

**Closed** 2020-02-29 00:54 UTC
Labels: duplicate
