### ISSUE TITLE
event listener for yaw change

### ISSUE THREAD

**Issue by INF800** [mpetroff/pannellum#1019] opened 2021-08-10 09:58 UTC
Do we have something like 
```js
viewer.on('yawchange', (e)=>{
    console.log(e)
})
```

so that we can get the yaw angle whenever user moves through panaroma?

**Comment by INF800** [comment] 2021-08-10 10:04
In documentation for [viewer.on(...)](https://www.hidemyass-freeproxy.com/proxy/en-in/aHR0cHM6Ly9wYW5uZWxsdW0ub3JnL2RvY3VtZW50YXRpb24vYXBpLw#on), it is mentioned that arg1 is *string* datatype. I am finding it very difficult to find list of all values that we can pass to arg1.

**Comment by INF800** [comment] 2021-08-10 10:17
I had to get into source code and find the string values by searching for `fireEvenet` call

![image](https://user-images.githubusercontent.com/45640029/128850195-d0379d3d-83a6-43bc-a89d-027fc7c98de4.png)

**Comment by INF800** [comment] 2021-08-10 10:18
> Do we have something like
> 
> ```js
> viewer.on('yawchange', (e)=>{
>     console.log(e)
> })
> ```
> 
> so that we can get the yaw angle whenever user moves through panaroma?

`animatefinished` seemed to do the job.

**Comment by mpetroff** [comment] 2021-08-10 13:43
The events are documented in [doc/events.md](https://github.com/mpetroff/pannellum/blob/master/doc/events.md), which is also included as [the API events section of the configuration reference webpage](https://pannellum.org/documentation/reference/#api-events).

The `animatefinished` event fires when viewer movement stops.

Otherwise, this issue is a direct duplicate of #310. Please search the existing issues before opening a new one.

**Closed by mpetroff** 2021-08-10 13:43 UTC
