### ISSUE TITLE
latest version new feature issue

### ISSUE THREAD

**Issue by fluidadsjtr** [mpetroff/pannellum#1012] opened 2021-07-26 08:30 UTC
I have taken a json that worked with the published/live pannellum and used it with the latest code.  I have noticed that if we switch scene via javascript api from one scene to another before the previous one has fully rendered when using multi-res (easier to replicate if also doing a rotation), the next scene does not render, and in fact no scenes thereon in render (without refreshing the browser).  The json does not use a sht or base64 image, the only difference is that we are referring to the latest pannellum.

Let me know if I need to provide more details, and a example of it failing and we will but a nice example together.

**Comment by mpetroff** [comment] 2021-07-26 14:16
I have not seen such behavior, so if you could provide an example, that would be useful.

**Comment by fluidadsjtr** [comment] 2021-08-20 11:23
Finally got a nice demo, go to the below link (I have not provided a thumbimage so when it goes wrong it goes black).

If you click the below it rapidly moves between scenes without problem, but click on a arrow and everything goes black and stays black, the only way to fix it is to refresh the page.  Bug is iphone and ipad, and also I get it mac but you might have to click a few arrows for it to fail.
https://yourvrtour.s3.eu-west-2.amazonaws.com/testhtml/demo_black.html

**Comment by mpetroff** [comment] 2021-08-25 14:34
I can reproduce the issue with an iPhone 5c and with Safari 14 through Sauce Labs. There are no errors in the console (in Sauce labs; I can't connect to the console on the iPhone without a Mac), but it stops making network requests for unclear reasons. Unfortunately, debugging this without a device with debug output that can reproduce it locally with be difficult.

**Comment by mpetroff** [comment] 2021-08-30 21:43
Since the bug was reproducible in Safari 10.3 (the newest version supported by my iPhone 5c), I was able to do sufficient testing to locate the commit that introduced the bug, 5eab5366f6987a4abdf648cbf5f7a243f14faf28. Then, with the help of print debugging to an on-screen element (lacking the ability to connect to the developer tools) and a fair amount of trial and error, I was able to figure out which optimization was at fault, which turned out to be the optimization that ensured texture loads were performed at the beginning of a frame. After forcing all browsers to use the non-web-worker-based tile loading method and reducing the number of simultaneous loads, I was able to reproduce the issue in Firefox, which allowed for proper debugging, although it still took a while to figure out what was happening and to implement a fix that was better than just removing the optimization.

It turns out that the tile loader objects (of which there are only 4) would sometimes be lost when the scene changed; once there were none left, tiles would stop loading. Only the non-web-worker-based tile loading method was affected. This was only an issue for Safari, since it is the only up-to-date browser that doesn't support the web-worker-based tile loading method (since it doesn't support the `createImageBitmap` method needed to transfer the images out of the worker) and was particularly prone to the issue because it is slow to load tiles.

The issue should be fixed in 2ea5f4b992d40d08e3d1f1532c9a83c241c6622d.

**Closed** 2021-08-30 21:43 UTC
Labels: bug
