### ISSUE TITLE
Firefox texture error.

### ISSUE THREAD

**Issue by sqrt11** [mpetroff/pannellum#505] opened 2017-11-16 17:27 UTC
Sometimes I try to load pannellum on firefox and image loads with some different colors or entire black.
When the image is black I got these 2 messages on console:

    "Error: WebGL warning: drawArrays: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive."
    "Image corrupt or truncated."

Firefox version is 56.0.2 (64-bit) with windows 10.

**Comment by sqrt11** [comment] 2017-11-16 17:30
Black Image Error:

![error-black-image](https://user-images.githubusercontent.com/9057566/32905981-c2743390-cae2-11e7-84e4-71c24e7b8548.PNG)

Color Error:

![error-color](https://user-images.githubusercontent.com/9057566/32905982-c2945198-cae2-11e7-8512-cc8f66722e80.PNG)

**Comment by mpetroff** [comment] 2017-11-17 03:05
This looks like a graphics card/driver issue.

**Comment by sqrt11** [comment] 2017-11-17 16:04
I reproduced the error on 4 different machines, in one of them the firefox version was 54.0.0 and the error did not occur, but when I upgraded to 57.0, it crashed in the first time.

**Comment by Tomcat128** [comment] 2017-11-19 09:02
It doesn't appear to me every time loading a scene, but I can confirm this issue with FF 57.0 or Quantum. Never had this problem before with older versions of FF. Chrome and MS Edge are still ok (on the same machine), so it seems to be a problem with the latest upgrade of FF.

![2017-11-19 09_54_04-mozilla firefox](https://user-images.githubusercontent.com/33800543/32989002-3f90b0cc-cd10-11e7-9e6f-1fc3b1b24e5d.png)

**Comment by mpetroff** [comment] 2017-11-21 02:18
I've never see this happen, and I don't recall any other people reporting similar issues. Unfortunately, I'm not sure if there's much I can do about it.

**Comment by DStillingfleet** [comment] 2017-11-25 08:02
Hi All

I also noticed this happening to my pannellum tours in Firefox yesterday, where as they used to work fine.  I'm also assuming it is related to a recent Firefox update.  Furthermore, if the tour is run locally from my hard drive there is no problem, it only affects tours on-line.

There appears to be no problem in Chrome for Windows, nor Chrome and Safari on my iPhone.

Regards

Derek

**Comment by tomato42** [comment] 2017-11-26 21:01
I've experienced the same on Linux with Firefox onj two different machines with a tour (with both Intel and AMD GPU)

what's interesting is that the server is on a local network from one of those machines. Also I don't think I ever saw it with the multires panorama...

could pannellum try to check if the file fully downloaded before setting it as webgl texture?

**Comment by mpetroff** [comment] 2017-11-26 22:08
@tomato42 There is no attempt to display an image before it is fully downloaded.

I've tested with Firefox 57 on six machines now, four Linux and two Windows 7 with either Intel or Nvidia GPUs, but still have not been able to reproduce this.

**Comment by tomato42** [comment] 2017-11-27 01:09
for me it happens about one in 20 to 30 transitions (with the server on a different machine), and the first time it happened was when the tour was around 14 scenes

for what it's worth, I'm using FF 57.0 (64-bit)

**Comment by mpetroff** [comment] 2017-12-01 04:34
I was finally able to reproduce this (the black screen & resulting error message). It only happened once. Unfortunately, I'm still not really any closer to figuring out what's happening.

**Comment by tomato42** [comment] 2017-12-01 13:28
seems to be a FF cache issue:
http://www.html5gamedevs.com/topic/17328-phaser-bug-when-reloading-page-with-f5/
https://github.com/pixijs/pixi.js/issues/3767
https://github.com/photonstorm/phaser/issues/2534

**Comment by humulus2** [comment] 2017-12-08 19:12
I have the same problem. 56.0.2 (64-bit) with windows 8.1
I notice the problem is often with bigger img 6000x3000. But when I try mobile ver. 4000x2000 it looks ok. 
Even when I open in diffrent FF cards desktop ver fail, mobile is ok.

**Comment by humulus2** [comment] 2017-12-08 19:19
I update FF to 57.0.2 and it seems all version desktop and mobile dont work. Next symptom is loading bar is stop on 100% and nothing happend (dont show panorama).

**Comment by humulus2** [comment] 2017-12-08 20:49
Correct me if I'm wrong but it look like problem is only with equirectangular panoramas? I convert to cube and it seems look ok.

**Comment by jimblue** [comment] 2017-12-15 00:31
I've fix this issue by disable nvidia web driver and cuda drive on macosx high sierra.

**Comment by EdouardDLMT** [comment] 2018-01-08 22:23
@jimblue sorry but how did you disabled nvidia web driver and cuda driver ?

**Comment by jimblue** [comment] 2018-01-08 22:50
by uninstalling them... 🙃

**Comment by jimblue** [comment] 2018-01-08 22:51
That said it's no really a fix

**Comment by ademarre** [comment] 2018-01-09 07:08
The issues I've seen appear to be resolved with Firefox 58 (currently beta).

**Comment by emaglic** [comment] 2018-01-17 20:47
This isn't exactly a solution but more of a contingency plan... 

Would it be possible to detect this error and have Pannellum display an error message and/or some kind of static '2D' fallback image instead? 

That way the end user would see something, and wouldn't be left with a black screen or something that looks corrupted.

**Comment by sqrt11** [comment] 2018-01-23 15:00
Firefox 58 was released today and as @ademarre said, the problem seens to be solved.

**Comment by DStillingfleet** [comment] 2018-01-23 17:20
Great news.

**Comment by EdouardDLMT** [comment] 2018-01-23 21:08
Yes I confirm on mac, we can close the subject, the only need is to update Firefox! !

**Comment by DStillingfleet** [comment] 2018-01-24 08:14
For what it’s worth, I can confirm the v58 update to Firefox has resolved the problems I saw too.

**Closed** 2018-01-24 13:55 UTC

**Comment by NWray-WIREWAX** [comment] 2018-11-13 15:55
I'm actually getting a very similar issue on 63.0.1.
It's reporting MANY of these errors:
"Error: WebGL warning: drawArrays: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive."

**Comment by tomato42** [comment] 2018-11-13 19:32
the bug is in Firefox, not panellum – it went away for me without updating panellum but with update to FIrefox
