### ISSUE TITLE
orientation on mobile device

### ISSUE THREAD

**Issue by AlaaElZein** [mpetroff/pannellum#413] opened 2017-06-20 11:24 UTC
Hello,
I am using the orientationOnByDefault to start the orientation automatically, and it is working fine, but on mobile when i re-use the tap (when i swipe the screen manually) the orientation stops, and it will not wor again until i hit the orientation button. So how i should keep the orientation working all times even if i use the swipe?

Regards,

**Comment by mpetroff** [comment] 2017-06-20 15:36
Duplicate of #364.

**Closed by mpetroff** 2017-06-20 15:36 UTC

**Comment by AlaaElZein** [comment] 2017-06-21 07:04
Hello,

As mentionned in the #364 , to solve this problem we have to add the startOrientation(); function at the end of the onDocumentTouchEnd() function.
I copied the pannellum.js file to my code and add this function as mentionned and still not working.

When i debug my code and make an alert at the beginning of onDocumentTouchEnd function the alert did not appear when i touch the screen. So the onDocumentTouchEnd function is not executed.
How can i make the onDocumentTouchEnd function triggered ?
