### ISSUE TITLE
Uncaught ReferenceError: DeviceMotionEvent is not defined

### ISSUE THREAD

**Issue by DamienSM** [mpetroff/pannellum#872] opened 2020-05-27 04:14 UTC
When orientationOnByDefault is on, but the browser doesn't support device motion, pannellum throws an exception and movement breaks.

`"function" === typeof DeviceMotionEvent.requestPermission ? DeviceOrientationEvent.requestPermission().then(function(a) {...`

Checking for DeviceMotionEvent fixes the problem:

`DeviceMotionEvent && "function" === typeof DeviceMotionEvent.requestPermission ? DeviceOrientationEvent.requestPermission().then(function(a) {...`

**Comment by mpetroff** [comment] 2020-05-27 14:18
This is a duplicate of #846, which has already been fixed (although I just fixed a typo in the original fix).

**Closed by mpetroff** 2020-05-27 14:18 UTC
