### ISSUE TITLE
event system

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#126] opened 2016-03-13 19:25 UTC
Hi,
Should be nice to get event on render done or other states changes.

You can find it done at https://github.com/Benvii/pannellum/commit/8035301a1b7d5dbfad50d808e2aa3b771c84a6cb

Cheers

**Comment by Cyrille37** [comment] 2016-03-13 19:52
or very very simple callback system like https://github.com/Cyrille37/pannellum/commit/7b14fa00965206198467841114e29e62272a7184

**Comment by mpetroff** [comment] 2016-03-14 22:35
This is a duplicate of #30. I've started on a design of an event system but haven't implemented it yet. It's something I hope to add before the next release.

**Closed by mpetroff** 2016-03-14 22:35 UTC
