### ISSUE TITLE
Marker rotation with yaw angle value taken from panoramic image

### ISSUE THREAD

**Issue by MASPCHINE** [mpetroff/pannellum#1081] opened 2022-02-25 06:25 UTC
Hi,

I am working on a website where we can view panoramic photos and scroll through the photos with the help of the library you have created.
Like this;
![image](https://user-images.githubusercontent.com/92780710/155662853-00276d7a-b1b1-4a82-a5b8-e7c02d3ce1f8.png)
I can get the yaw angle of the panoramic image with the getYaw() method in the library. I use mousedown function as mouse event and I can get yaw angle as a result of every mousedown movement on the panoramic image.

Like this;
![image](https://user-images.githubusercontent.com/92780710/155663902-a89ef215-9410-4f11-ab91-822a8eb90c12.png)

With the help of this data I received, I want to add a marker that can move according to the yaw angle, like the compass you added.

![image](https://user-images.githubusercontent.com/92780710/155664805-d004a05a-35cb-4016-9a51-3251499bb0cc.png)

but when I send the values ​​of the yaw angle I obtained to the yaw angle value of the marker, I can only send the last yaw angle value and the next marker is rotated according to the yaw angle value I obtained. How can I get the dynamic structure that works like the compass you added?

Thank you for your reply...

**Comment by mpetroff** [comment] 2022-02-26 16:14
I'm not entirely certain what you mean by "I can only send the last yaw angle value and the next marker is rotated according to the yaw angle value I obtained" or by "the dynamic structure."

If you mean a value that updates whenever the yaw value changes, there's currently no good way to do that. In that case, this question is a duplicate of #310.

**Comment by MASPCHINE** [comment] 2022-02-26 22:53
actually what I want to add is to create like the compass you added. Can I add something like this or change the display properties of the compass from within the library?

**Comment by MASPCHINE** [comment] 2022-02-26 22:54
actually what i want to add is to create like the compass you add. Can I add something like this or change the display properties of the compass from the library?

**Comment by mpetroff** [comment] 2022-02-27 18:28
Okay, but to do that outside the viewer would require an event listener that's triggered when the yaw value changes, which is something that doesn't currently exist. Otherwise, you'd have to edit the library itself and add something into the `render()` function.

If you want to just change the look of the existing compass, you can override the CSS (`pnlm-compass` class).

**Comment by MASPCHINE** [comment] 2022-02-27 20:08
thank you for your reply

**Closed** 2022-03-01 11:30 UTC
Labels: question
