### ISSUE TITLE
Pannellum.org homepage throwing error

### ISSUE THREAD

**Issue by JamieBradley** [mpetroff/pannellum#648] opened 2018-08-23 12:48 UTC
Uncaught TypeError: Cannot read property 'drawingBufferWidth' of null

Chrome Version 67.0.3396.99 (Official Build) (64-bit) running on OS X Yosemite.

**Comment by mpetroff** [comment] 2018-08-24 18:33
Duplicate of #583. Fixed in c471a06c32cecaa5e2d3c68bdbc73f9d1adb8739.

**Closed by mpetroff** 2018-08-24 18:33 UTC
