### ISSUE TITLE
Fullscreen Button iPhone / iOS

### ISSUE THREAD

**Issue by rimmeh** [mpetroff/pannellum#988] opened 2021-05-20 08:09 UTC
HI,

we have an Issue with Apple devices. The Fullscreen Button is missing, even if we Force the Button to appear the Fullscreen Overlay is not opening on iPhones.

The issue is present too on Main demo of startpage from  panellum.org.

Any Suggestions how to fix this?

**Comment by mpetroff** [comment] 2021-05-20 13:53
Apple doesn't support the fullscreen API on iPhones. Duplicate of #915, #467, #313, #309, and #66.

**Closed by mpetroff** 2021-05-20 13:53 UTC
