### ISSUE TITLE
Black squares on multires panorama on low screen size

### ISSUE THREAD

**Issue by ArFnds** [mpetroff/pannellum#1204] opened 2024-02-05 07:59 UTC
When displaying the multires example on mobile, or by adjusting the width, some tiles does not display :

![image](https://github.com/mpetroff/pannellum/assets/112687932/283b0ff5-935d-4725-a163-0efe9bc53b20)
![image](https://github.com/mpetroff/pannellum/assets/112687932/41a2fc34-82fc-4762-b3dc-d443929cffe8)

Step to reproduce: 
- Load the sample on an standalone page
- Lower the width of the screen using Developers Tools or load it on a mobile phone
- Rotate until it happens 

Looks like this one : #786

**Comment by mpetroff** [comment] 2024-02-05 15:05
Which version of Pannellum and what browser and browser version are you using?

In #786, the issue was that there were missing tiles while the panorama was loading (which has since been resolved with the addition of spherical harmonics based previews). My interpretation of what you're reporting is that the tiles never load, which would be a different issue.

**Comment by ArFnds** [comment] 2024-02-05 15:21
I have build the project from the `master` branch.

Mobile:
- Safari on iOs
- Chrome 121 on Android
- Yandex 24 on windows (Chromium based)

On mobile, the black squares disappear after a few moment, it seems to load little tiles. But I am on the same Wifi as my computer (which has no problem on full size), and my phone is not old (Samsumg S21).

Maybe le tiles are loaded again and again from internet, which can cause this "always loading tiles issue" on mobile.

I may not be pointing the right problem. Here is a gif of the issue when resizing on computer :
https://freeimage.host/i/J0Dj0vI

**Closed** 2024-02-06 01:31 UTC

**Comment by mpetroff** [comment] 2024-02-06 01:34
This was a regression due to a bug in an optimization introduced in 05dae19b2806fd01665351ab0f83a8bd203494ed. I fixed the bug in 8f7a888c3a108b2bcf9b961341bb0faa4ce627d3 and further improved the optimization in 021b512fa80f0e987332d11debe14a4cc55052d7, which reduces the unnecessary drawing of tiles that have their children drawn on top of them, reducing the total number of draw calls per frame.
