### ISSUE TITLE
Hot Spot im Vordergrund

### ISSUE THREAD

**Issue by StadtGE** [mpetroff/pannellum#1117] opened 2022-09-01 09:26 UTC
Hallo,
ist es möglich einen Hot Spot so zu konfigurieren, dass dieser im Vordergrund liegt?
Ich habe das Problem, das bei eng nebeneinanderliegenden Icons das Textfeld (hover) von einem Icon überdeckt wird und man nicht mehr die Schrift lesen kann.
Über Hilfen wäre ich dankbar.

Grüße
Eva

**Comment by mpetroff** [comment] 2022-09-03 23:48
Quoting from the readme:
> Please make an attempt to write in grammatically-correct English on the issue tracker; using the results of machine translation is acceptable if one in not fluent in the language, and attempts to work past language barriers will be made.

I don't speak German.

**Comment by StadtGE** [comment] 2022-09-05 07:34
hi, sorry,

Hello
is it possible to configure a hot spot so that it is in the front?
I have the problem that with closely adjacent icons the text field (hover) is covered by an icon and you can no longer read the font.
I would be grateful for help.

Greetings
Eva

**Comment by mpetroff** [comment] 2022-09-18 20:59
If I correctly understand your issue, your hot spot tool tip is being covered by another hot spot icon. This shouldn't happen, and I am unable to reproduce the issue with either the current Git `master` branch or with release v2.5.6. It works as designed, with the tool tip over the hot spot icon:
![Screenshot from 2022-09-18 16-55-06](https://user-images.githubusercontent.com/1450212/190927867-9f5ef338-ffcf-47c4-91dd-7cd962bf440b.png)

Can you link to an example that shows the issue?

**Comment by mpetroff** [comment] 2022-11-08 01:13
Fixed in 6b6d6deac92f7d38330a6d2f62606064b2da2ed4.

**Closed by mpetroff** 2022-11-08 01:13 UTC
