### ISSUE TITLE
iPhone Issue

### ISSUE THREAD

**Issue by raffaelecolleo** [mpetroff/pannellum#309] opened 2016-12-02 05:28 UTC
Hi All,
I can see the fullscreen button on an android device but cannot see it on an iphone device.

Any Ideas?

**Comment by mpetroff** [comment] 2016-12-02 20:59
Complain to Apple. They don't support the full screen API: http://caniuse.com/#feat=fullscreen

Duplicate of #66.

**Closed by mpetroff** 2016-12-02 20:59 UTC
