### ISSUE TITLE
view changed event

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#425] opened 2017-07-07 14:44 UTC
It would be great for some applications if pannellum emits a new event when the yaw/pitch/hfov is changed. Currently I have to listen to the low level mousemove, touchmove, pointermove, mousedown, touchstart, mouseup, touchend events.

**Comment by mpetroff** [comment] 2017-07-09 17:21
Duplicate of #310, which you already commented on.

**Closed by mpetroff** 2017-07-09 17:21 UTC
