### ISSUE TITLE
Feature request: add touchstart event to event listener of clickHandleFunc

### ISSUE THREAD

**Issue by ssoldy** [mpetroff/pannellum#933] opened 2020-11-08 20:12 UTC
Hello while testing my webapp on mobile I found out that click event doesn't always work on mobile devices while adding touchstart does, maybe this is useful for other people too.

```javascript
    if (hs.clickHandlerFunc) {
        div.addEventListener('click', function(e) {
            hs.clickHandlerFunc(e, hs.clickHandlerArgs);
        }, 'false');
        div.addEventListener('touchstart', function(e) {
            hs.clickHandlerFunc(e, hs.clickHandlerArgs);
        }, 'false');
        div.className += ' pnlm-pointer';
        span.className += ' pnlm-pointer';
    }
```

**Comment by mpetroff** [comment] 2020-11-18 16:35
This is duplicate of #861 and #926 and was fixed in 6075769935a27e61c9e1f0f656f8cef532abaa77 (but the fix has not yet made it into a release).

**Closed by mpetroff** 2020-11-18 16:35 UTC
